apiVersion: apps/v1
kind: Deployment
metadata:
  name: crewai-api
  namespace: crewai
spec:
  replicas: 3
  selector:
    matchLabels:
      app: crewai-api
  template:
    metadata:
      labels:
        app: crewai-api
    spec:
      containers:
      - name: crewai-api
        image: rogerio1994/crewaiapi:latest
        ports:
        - containerPort: 8000
        resources:
          requests:
            cpu: "250m"
            memory: "512Mi"
          limits:
            cpu: "500m"
            memory: "1Gi"
---
apiVersion: v1
kind: Service
metadata:
  name: crewai-api-service
  namespace: crewai
spec:
  selector:
    app: crewai-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: crewai-api-pdb
  namespace: crewai
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: crewai-api
